"""Added phone_number field to User model

Revision ID: 995f7fbd8946
Revises: f49224c0b3c2
Create Date: 2025-12-13 17:57:41.888495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995f7fbd8946'
down_revision = 'f49224c0b3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
