"""replace image_path with current_environment

Revision ID: a9b0c8edadad
Revises: 995f7fbd8946
Create Date: 2025-12-21 20:45:51.254708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9b0c8edadad'
down_revision = '995f7fbd8946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compilation_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_environment', sa.String(length=32), nullable=False))
        batch_op.alter_column('output_format',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=8),
               existing_nullable=True)
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compilation_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.alter_column('output_format',
               existing_type=sa.String(length=8),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=True)
        batch_op.drop_column('current_environment')

    # ### end Alembic commands ###
